### PR TITLE
[#175126219] Add healthcheck in deploy pipeline before swap staging slot

### PR DESCRIPTION
**Pull request by infantesimone**
This PR change default _deployType_ to _deployToStagingSlotAndSwap_ and add _Healthcheck_ step to check staging slot runtime configuration invoking /info endpoint.

### CODE REVIEW

**Comment by gunzip** [comment]
aren't these files supposed to be imported from a remote template repository? cc @balanza

**Comment by infantesimone** [comment]
that's true, sorry

**Comment by balanza** [comment]
> aren't these files supposed to be imported from a remote template repository? cc @balanza

That's the idea, although I'm having some syntax issues in this other PR https://github.com/pagopa/io-functions-assets/pull/13

**Comment by balanza** [comment]
@infantesimone why draft?

**Comment by infantesimone** [comment]
the task is completed but is to be tested

**Review by balanza — COMMENTED** [review]
LGTM

**Comment by gunzip** [comment]
I'm merging this (autoswap is already disabled)

**Pull request merged**
